name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}
        run: ./gradlew :app:testDebugUnitTest  # Run unit tests in the 'app' module

      - name: Run instrumented tests
        run: ./gradlew :app:connectedCheck  # Run instrumented tests in the 'app' module

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token from GitHub Secrets
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}  # Project key from GitHub Secrets
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}  # Organization from GitHub Secrets
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=$SONAR_ORGANIZATION \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
