name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Android Tests Reporter
        uses: FlickerSoul/android-test-report-actions@v1.3.1

      - name: Run Android instrumentation tests
        uses: emulator-wtf/run-tests@v0.9.10




