name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Android Github Action
        uses: vukan-markovic/Github-Android-Action@1.2

      - name: Run instrumented tests
        run: ./gradlew :app:connectedCheck  # Run instrumented tests in the 'app' module

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token from GitHub Secrets
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}  # Project key from GitHub Secrets
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}  # Organization from GitHub Secrets
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=$SONAR_ORGANIZATION \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
